# Generated by Django 4.2.1 on 2023-05-26 12:20

import My_Plant_App.web.validators.custom_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(choices=[('OUTDOOR PLANTS', 'Outdoor Plants'), ('INDOOR PLANTS', 'Indoor Plants')], max_length=14)),
                ('name', models.CharField(validators=[django.core.validators.MinLengthValidator(2), My_Plant_App.web.validators.custom_validators.validate_name_contains_only_letters])),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[My_Plant_App.web.validators.custom_validators.validate_first_letter_is_upper], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, validators=[My_Plant_App.web.validators.custom_validators.validate_first_letter_is_upper], verbose_name='Last Name')),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
