# Generated by Django 4.2.2 on 2023-06-24 08:01

import Exam.web.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_fruitmodel_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=18, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), Exam.web.models.validate_profile_name], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1), Exam.web.models.validate_profile_name], verbose_name='Last Name'),
        ),
    ]
